---
display_name: Temp. automation
job_name: temperature_automation
subtext: automation_name
display: true
source: app
description: Start a temperature automation to control the culture's temperature.
published_settings:
  - key: target_temperature
    unit: ℃
    label: Target temperature
    type: numeric
    description: Change the target temperature. Lower bound is the ambient temperature, and upperbound is 50℃. Only used in when Thermostat automation is active.
    default: null
    display: true
  - key: automation_name
    type: string
    display: false
    default: ""
